# worker_processes auto;

# events {
#     worker_connections 1024;
# }

# http {
#     include mime.types;
#     default_type application/octet-stream;
#     sendfile on;
#     keepalive_timeout 65;

#     # ==================================
#     # 1200 request / hour لكل IP
#     # 20 request / minute
#     # ==================================
#     limit_req_zone $binary_remote_addr zone=hour_limit:10m rate=20r/60m;

#     server {
#         listen 80;

#         location / {

#             # يسمح لحد 1200 في الساعة
#             # burst = 200 => من 1000 لحد 1200
#             limit_req zone=hour_limit burst=200 nodelay;

#             root /usr/share/nginx/html;
#             index index.html;
#             try_files $uri /index.html;
#         }
#     }
# }
